version : '2'

services:
  wallet:
    image: daniellavoie/confluent-microservices-wallet:${WALLET_VERSION}
    restart: always
    mem_limit: 1g
    networks:
    - traefik
    - default
    labels:
    - "traefik.backend=it.wallet.confluent.daniellavoie.dev"
    - "traefik.frontend.rule=Host:it.wallet.confluent.daniellavoie.dev"
    - "traefik.port=80"
    - "traefik.docker.network=traefik_webgateway"
    environment:
      WALLET_KAFKA_BOOTSTRAP_SERVERS: kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,PUBLIC://it.confluent.daniellavoie.dev:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PUBLIC:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - "${KAFKA_PORT}:${KAFKA_PORT}"

networks:
  traefik:
    external:
      name: traefik_webgateway